# Generated by Django 3.2.3 on 2022-03-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scrap_movie',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
