# Generated by Django 3.2.3 on 2022-03-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220311_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
