# Generated by Django 3.2.3 on 2022-03-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_rating'),
        ('accounts', '0008_alter_user_category_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category_list',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
    ]
