# Generated by Django 3.2.3 on 2021-11-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='genres_ids',
        ),
    ]
