# Generated by Django 3.2.3 on 2021-11-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_genres_movie_genres_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres_ids',
            new_name='genre_ids',
        ),
    ]
