# Generated by Django 3.2.3 on 2021-11-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_genres_ids_movie_genre_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_ids',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
    ]
