# Generated by Django 3.2.3 on 2021-11-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20211121_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
