# Generated by Django 3.2.3 on 2022-03-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20211124_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_path', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(to='movies.Cast'),
        ),
    ]
