# Generated by Django 3.2.3 on 2022-03-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_onelinereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onelinereview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onelinereviews', to='movies.movie'),
        ),
    ]
