# Generated by Django 3.2.3 on 2022-03-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
