# Generated by Django 3.2.3 on 2021-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
