# Generated by Django 3.2.3 on 2021-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_title',
            field=models.CharField(max_length=500),
        ),
    ]
