# Generated by Django 3.2.3 on 2021-11-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_review_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
